version: '3.1'

services:
  db:
    build: ./database
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=recipes
      - POSTGRES_USER=recipes
      - POSTGRES_PASSWORD=password123
