version: '3.1'

services:
  db:
    build: ./database
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=recipes
      - POSTGRES_USER=recipes
      - POSTGRES_PASSWORD=password123

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.local
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server:cached
    env_file:
      - ./server/.env # AWS credentials
    environment:
      - ROCKET_DATABASES={recipes={url="postgres://recipes:password123@db:5432/recipes"}}
