version: '3.1'

services:
  db:
    build: ./database
    ports:
      - "5432:5432"
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.local
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server:cached
