version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.2.0
  # jobs:
  # build-server:
  # docker:
  # - machine: ubuntu-1604:201903-01
  # steps:
  # - checkout
  # - run:
  # name: Build Dockerfile
  # command: |
  # cd server
  # docker build -t recipes-server .
  # - run:
  # name: Push to ECR
  # command: |
  # $(aws ecr get-login --no-include-email)
  # docker tag recipes-server 744937614989.dkr.ecr.eu-west-2.amazonaws.com/recipes
  # docker push 744937614989.dkr.ecr.eu-west-2.amazonaws.com/recipes
  # 
  # build-client:
  # docker:
  # - image: node:lts
  # steps:
  # - checkout
  # - run:
  # name: Version information
  # command: node --version; yarn --version
  # - run:
  # name: Install dependencies
  # command: cd client; yarn
  # - run:
  # name: Build
  # command: cd client; yarn build
  # 
workflows:
  build-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          checkout: true
          create-repo: false
          path: server
          region: AWS_REGION
          repo: recipes
          tag: recipes-server:latest

      # - build-client

        # - deploy-server:
        # requires:
        # - build-server
        # filters:
        # branches:
        # only: master
