version: 2.1
jobs:
  build-server:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: Rustup
          command: rustup toolchain install nightly; rustup default nightly
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Change directory
          command: cd server
      - run:
          name: Build
          command: cargo build

  build-client:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run:
          name: Version information
          command: node --version; yarn --version
      - run:
          name: Change directory
          command: cd client
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build


workflows:
  build-deploy:
    jobs:
      - build-server
      - build-client
        # - deploy-server:
        # requires:
        # - build-server
        # filters:
        # branches:
        # only: master
