version: 2.1

executors:
  orb-executor:
    docker:
      - image: circleci/python:3.7.1

orbs:
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-ecs: circleci/aws-ecs@0.0.11

jobs:
  - build-server:
      executor: orb-executor
      steps:
        - aws-ecr/build-and-push-image:
            account-url: AWS_ECR_ACCOUNT_URL
            aws-access-key-id: AWS_ACCESS_KEY_ID
            aws-secret-access-key: AWS_SECRET_ACCESS_KEY
            checkout: true
            create-repo: true
            dockerfile: server/Dockerfile
            path: server
            region: AWS_REGION
            repo: recipes-server
            tag: ${CIRCLE_SHA1}

  - deploy-server:
      executor: orb-executor
      steps:
        - aws-ecs/deploy-service-update:
            requires:
              - aws-ecr/build-and-push-image
            family: 'recipes-task-definition'
            cluster-name: 'recipes'
            service-name: 'recipes-service'
            container-image-name-updates: 'container=recipes-server,tag=${CIRCLE_SHA1}'

workflows:
  build-deploy:
    jobs:
      - build-server
      - deploy-server:
          requires:
            - build-server
          filters:
            branches:
              only: master
