version: 2.1
jobs:
  build-server:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: Rustup
          command: rustup toolchain install nightly; rustup default nightly
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Build
          command: cd server; cargo build --release
      - persist_to_workspace:
          root: server
          paths:
            - target

  deploy-server:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - attach_workspace:
          at: /tmp/recipes
      - run:
          name: Package
          command: tar -cfz release.tar.gz /tmp/recipes/target/release
      - run:
          name: Copy
          command: scp release.tar.gz ec2-user@ec2-35-177-170-145.eu-west-2.compute.amazonaws.com:/home/ec2-user

  build-client:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run:
          name: Version information
          command: node --version; yarn --version
      - run:
          name: Install dependencies
          command: cd client; yarn
      - run:
          name: Build
          command: cd client; yarn build

workflows:
  build-deploy:
    jobs:
      - build-server
      - build-client
        # - deploy-server:
        # requires:
        # - build-server
        # filters:
        # branches:
        # only: master
