version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-ecs: circleci/aws-ecs@0.0.11
  aws-s3: circleci/aws-s3@1.0.16

jobs:
  client:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - aws-s3/sync:
          # arguments: |
          #   --acl public-read \
          #   --cache-control "max-age=86400"
          from: ./dist
          overwrite: true
          to: 's3://recipes.elliotdavies.co.uk'

      # - aws-ecr/build-and-push-image:
      #     name: build-server
      #     account-url: AWS_ECR_ACCOUNT_URL
      #     aws-access-key-id: AWS_ACCESS_KEY_ID
      #     aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      #     checkout: true
      #     create-repo: true
      #     dockerfile: server/Dockerfile
      #     path: server
      #     region: AWS_REGION
      #     repo: recipes-server
      #     tag: ${CIRCLE_SHA1}

      # - aws-ecr/build-and-push-image:
      #     name: build-client
      #     account-url: AWS_ECR_ACCOUNT_URL
      #     aws-access-key-id: AWS_ACCESS_KEY_ID
      #     aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      #     checkout: true
      #     create-repo: true
      #     dockerfile: client/Dockerfile
      #     path: client
      #     region: AWS_REGION
      #     repo: recipes-client
      #     tag: ${CIRCLE_SHA1}

#       - aws-ecs/deploy-service-update:
#           requires:
#             - build-server
#           filters:
#             branches:
#               only: master
#           family: 'recipes-server' # Task definition
#           cluster-name: 'recipes'
#           service-name: 'recipes-server'
#           container-image-name-updates: 'container=recipes-server,tag=${CIRCLE_SHA1}'

      # - aws-ecs/deploy-service-update:
      #     requires:
      #       - build-client
      #     filters:
      #       branches:
      #         only: master
      #     family: 'recipes-client' # Task definition
      #     cluster-name: 'recipes'
      #     service-name: 'recipes-client'
      #     container-image-name-updates: 'container=recipes-client,tag=${CIRCLE_SHA1}'

workflows:
  build-deploy:
    jobs:
      - client
