version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.16

jobs:
  build-client:
    docker:
      - image: cimg/node:lts
    working_directory: ~/recipes/client
    steps:
      - checkout:
          path: ~/recipes
      - run:
          name: Install
          command: yarn
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy-client:
    docker:
      - image: cimg/python:3.7
    steps:
      - attach_workspace:
          at: .
      - aws-s3/copy:
          arguments: |
            --recursive
          from: dist
          to: 's3://recipes.elliotdavies.co.uk'

  build-deploy-server:
    docker:
      - image: cimg/node:lts
    working_directory: ~/recipes/serverless
    steps:
      - checkout:
          path: ~/recipes
      - run:
          name: Install
          command: yarn
      - run:
          name: Deploy
          command: yarn deploy

workflows:
  build-deploy-server:
    jobs:
      - build-deploy-server

  build-deploy-client:
    jobs:
      - build-client
      - deploy-client:
          requires:
            - build-client
