service: recipes-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-west-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
