service: recipes-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-west-2
  vpc:
    securityGroupIds:
      - sg-09cdfc1f01f29b459

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      PGHOST: ${env:PGHOST}
      PGDATABASE: ${env:PGDATABASE}
      PGUSER: ${env:PGUSER}
      PGPASSWORD: ${env:PGPASSWORD}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 8000
    noPrependStageInUrl: true
    preserveTrailingSlash: true
