service: recipes-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
      Resource:
        - "arn:aws:dynamodb:eu-west-2:744937614989:table/recipes"
        - "arn:aws:dynamodb:eu-west-2:744937614989:table/recipes/index/RecipesByUser"
        - "arn:aws:dynamodb:eu-west-2:744937614989:table/recipes_users"
        - "arn:aws:dynamodb:eu-west-2:744937614989:table/recipes_users_basic"
        - "arn:aws:dynamodb:eu-west-2:744937614989:table/recipes_sessions"
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::recipes.elliotdavies.co.uk/*"
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 8000
    noPrependStageInUrl: true
    preserveTrailingSlash: true
