service: recipes-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-west-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      PGHOST: ${env:PGHOST}
      PGDATABASE: ${env:PGDATABASE}
      PGUSER: ${env:PGUSER}
      PGPASSWORD: ${env:PGPASSWORD}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-domain-manager

custom:
  serverless-offline:
    httpPort: 8000
    noPrependStageInUrl: true
    preserveTrailingSlash: true
  customDomain:
    domainName: api.recipes.elliotdavies.co.uk
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
