FROM clux/muslrust:stable

ENV ROCKET_DATABASES '{recipes={url="postgres://recipes:password123@db:5432/recipes"}}'

WORKDIR /server

RUN rustup toolchain install nightly-2019-08-09 && \
    rustup default nightly-2019-08-09

RUN rustup target add x86_64-unknown-linux-musl

RUN cargo install cargo-watch

CMD cargo watch -x run
