CREATE TABLE IF NOT EXISTS recipes (
    id    SERIAL PRIMARY KEY,
    url   VARCHAR NOT NULL,
    notes VARCHAR NOT NULL
);

ALTER TABLE recipes ADD COLUMN IF NOT EXISTS title VARCHAR NOT NULL DEFAULT '';

ALTER TABLE recipes ADD COLUMN IF NOT EXISTS images VARCHAR[] NOT NULL DEFAULT '{}';

CREATE TABLE IF NOT EXISTS users (
    email VARCHAR NOT NULL UNIQUE PRIMARY KEY,
    name  VARCHAR
);

CREATE TABLE IF NOT EXISTS sessions (
    user_email VARCHAR REFERENCES users(email),
    session_id UUID NOT NULL,
    PRIMARY KEY (user_email, session_id)
);
