CREATE TABLE IF NOT EXISTS recipes (
    id    SERIAL PRIMARY KEY,
    url   VARCHAR NOT NULL,
    notes VARCHAR NOT NULL
);

ALTER TABLE recipes ADD COLUMN IF NOT EXISTS title VARCHAR NOT NULL DEFAULT '';
